@startuml

title __INPUTFORAPI's Class Diagram__\n

  namespace com.cs360.simplestocks.stock_api {
    namespace inputForApi {
      interface com.cs360.simplestocks.stock_api.inputForApi.ApiParameter {
          {abstract} + getKey()
          {abstract} + getValue()
      }
    }
  }
  

  namespace com.cs360.simplestocks.stock_api {
    namespace inputForApi {
      class com.cs360.simplestocks.stock_api.inputForApi.ApiParameterBuilder {
          - urlBuilder : StringBuilder
          + ApiParameterBuilder()
          + append()
          + append()
          + getUrl()
      }
    }
  }
  

  namespace com.cs360.simplestocks.stock_api {
    namespace inputForApi {
      enum Function {
        AD
        ADOSC
        ADX
        ADXR
        APO
        AROON
        AROONOSC
        ATR
        BBANDS
        BOP
        CCI
        CMO
        CURRENCY_EXCHANGE_RATE
        DEMA
        DIGITAL_CURRENCY_DAILY
        DIGITAL_CURRENCY_INTRADAY
        DIGITAL_CURRENCY_MONTHLY
        DIGITAL_CURRENCY_WEEKLY
        DX
        EMA
        HT_DCPERIOD
        HT_DCPHASE
        HT_PHASOR
        HT_SINE
        HT_TRENDLINE
        HT_TRENDMODE
        KAMA
        MACD
        MACDEXT
        MAMA
        MFI
        MIDPOINT
        MIDPRICE
        MINUS_DI
        MINUS_DM
        MOM
        NATR
        OBV
        PLUS_DI
        PLUS_DM
        PPO
        ROC
        ROCR
        RSI
        SAR
        SECTOR
        SMA
        STOCH
        STOCHF
        STOCHRSI
        T3
        TEMA
        TIME_SERIES_DAILY
        TIME_SERIES_DAILY_ADJUSTED
        TIME_SERIES_INTRADAY
        TIME_SERIES_MONTHLY
        TIME_SERIES_MONTHLY_ADJUSTED
        TIME_SERIES_WEEKLY
        TIME_SERIES_WEEKLY_ADJUSTED
        TRANGE
        TRIMA
        TRIX
        ULTOSC
        WILLR
        WMA
        urlParameter
      }
    }
  }
  

  namespace com.cs360.simplestocks.stock_api {
    namespace inputForApi {
      class com.cs360.simplestocks.stock_api.inputForApi.Symbol {
          - symbol : String
          + Symbol()
          + getKey()
          + getValue()
      }
    }
  }
  

  com.cs360.simplestocks.stock_api.inputForApi.Function .up.|> com.cs360.simplestocks.stock_api.inputForApi.ApiParameter
  com.cs360.simplestocks.stock_api.inputForApi.Symbol .up.|> com.cs360.simplestocks.stock_api.inputForApi.ApiParameter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
